# Generated by Django 5.0.2 on 2024-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_txt', models.CharField(blank=True, default='default_value', max_length=50)),
                ('temp', models.FloatField(blank=True, default=0)),
                ('icon', models.CharField(blank=True, default='default_value', max_length=50)),
            ],
            options={
                'ordering': ['dt_txt'],
                'managed': True,
            },
        ),
    ]
