# Generated by Django 5.0.2 on 2024-05-23 09:31

import BlogApp.enums
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Atelier', models.CharField(blank=True, default='XXX', max_length=50)),
                ('VAR_AFF_AT', models.BooleanField(default=1)),
            ],
            options={
                'ordering': ['Libelle_Atelier'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Infos_Des',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Info_Des', models.CharField(blank=True, default='Com', max_length=50)),
                ('Descritpion_Info_Des', models.CharField(blank=True, default='None', max_length=200)),
            ],
            options={
                'ordering': ['Libelle_Info_Des'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListeAttenteOrdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_AFFAIRE', models.IntegerField(blank=True, default=0)),
                ('DATE_DEBUT_ORDO', models.CharField(blank=True, default=0, max_length=50)),
                ('CLIENT', models.CharField(blank=True, default='ICAM', max_length=200)),
                ('ETAT_AFFAIRE', models.CharField(blank=True, default='X', max_length=50)),
                ('RANG_OF', models.CharField(blank=True, default='X', max_length=50)),
                ('TEMPS_PREVU', models.CharField(blank=True, default=0, max_length=50)),
                ('TEMPS_ECOULE', models.CharField(blank=True, default=0, max_length=50)),
                ('TEMPS_RESTANT', models.CharField(blank=True, default=0, max_length=50)),
            ],
            options={
                'ordering': ['DATE_DEBUT_ORDO'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ordres_Frabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_OF', models.CharField(blank=True, default='XXX', max_length=50, unique=True)),
                ('Nom_Piece', models.CharField(blank=True, default='Piece XXX', max_length=50)),
                ('Temps_Prevu', models.FloatField(blank=True, default=0)),
                ('Date_Debut', models.DateTimeField(blank=True)),
                ('Phase_OF', models.IntegerField(blank=True, default=0)),
                ('Rang_OF', models.CharField(blank=True, default='X', max_length=50)),
            ],
            options={
                'ordering': ['Ref_OF'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanChargeAtelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COSECT', models.CharField(blank=True, default='ATXXX', max_length=10)),
                ('ANNEE', models.IntegerField(blank=True, default=0)),
                ('SEMAINE', models.IntegerField(blank=True, default=0)),
                ('COFRAIS', models.CharField(blank=True, default='XXX', max_length=50)),
                ('DESIGN', models.CharField(blank=True, default='MACHINE XXX', max_length=200)),
                ('VDUREE', models.FloatField(blank=True, default=0)),
            ],
            options={
                'ordering': ['COFRAIS'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COSECT', models.CharField(blank=True, default='ATXXX', max_length=10, unique=True)),
                ('Libelle_Site', models.CharField(blank=True, default='Site XXX', max_length=50)),
            ],
            options={
                'ordering': ['COSECT'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_txt', models.CharField(blank=True, default='default_value', max_length=50)),
                ('temp', models.FloatField(blank=True, default=0)),
                ('icon', models.CharField(blank=True, default='default_value', max_length=50)),
            ],
            options={
                'ordering': ['dt_txt'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Absence', models.CharField(blank=True, default='Abs', max_length=50)),
                ('Type_Absence', models.CharField(blank=True, default='None', max_length=50)),
                ('Commentaire_Absence', models.CharField(blank=True, default='None', max_length=200)),
                ('Atelier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier')),
            ],
            options={
                'ordering': ['Libelle_Absence'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Infos_Asc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Info_Asc', models.CharField(blank=True, default='Info', max_length=50)),
                ('Descritpion_Info_Asc', models.CharField(blank=True, default='None', max_length=200)),
                ('Destinataire', models.CharField(blank=True, default='None', max_length=50)),
                ('Atelier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier')),
            ],
            options={
                'ordering': ['Libelle_Info_Asc'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asso_Atelier_Info_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atelier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier')),
                ('Info_Des_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.infos_des')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COFRAIS', models.CharField(blank=True, default='XXX', max_length=10, unique=True)),
                ('DESIGN', models.CharField(blank=True, default='Machine XXX', max_length=50)),
                ('VAR_AFF', models.BooleanField(default=1)),
                ('Atelier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier')),
                ('Site_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.site', to_field='COSECT')),
            ],
            options={
                'ordering': ['COFRAIS'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VDUREE', models.FloatField(blank=True, default=0)),
                ('ANNEE', models.IntegerField(blank=True, default=0)),
                ('SEMAINE', models.IntegerField(blank=True, default=0)),
                ('Poste_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.poste', to_field='COFRAIS')),
            ],
            options={
                'ordering': ['VDUREE'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asso_Postes_OF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OF_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.ordres_frabrication', to_field='Ref_OF')),
                ('Poste_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.poste', to_field='COFRAIS')),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default=BlogApp.enums.SetupStatus['active'], enum_class=BlogApp.enums.SetupStatus, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_interval', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('5 secs', '5 secs'), ('10 secs', '10 secs'), ('30 secs', '30 secs'), ('1 min', '1 min'), ('5 mins', '5 mins'), ('1 hour', '1 hour')], default=BlogApp.enums.TimeInterval['ten_secs'], enum_class=BlogApp.enums.TimeInterval, max_length=7)),
                ('nom_site', models.CharField(default='ATCRM', max_length=70)),
                ('nom_atelier', models.CharField(default='XXX', max_length=70)),
                ('num_semaine', models.IntegerField(blank=True, default=0)),
                ('num_annee', models.IntegerField(blank=True, default=0)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
            },
        ),
        migrations.AddField(
            model_name='atelier',
            name='At_Site_ID',
            field=models.ForeignKey(default='ATCRM', on_delete=django.db.models.deletion.CASCADE, to='BlogApp.site', to_field='COSECT'),
        ),
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Accident', models.CharField(blank=True, default='Acc', max_length=50)),
                ('Description_Accident', models.CharField(blank=True, default='None', max_length=200)),
                ('Site_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.site')),
            ],
            options={
                'ordering': ['Libelle_Accident'],
                'managed': True,
            },
        ),
    ]
