# Generated by Django 5.0.2 on 2024-05-31 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordres_frabrication',
            options={'managed': True, 'ordering': ['GACLEUNIK']},
        ),
        migrations.RenameField(
            model_name='ordres_frabrication',
            old_name='Ref_OF',
            new_name='GACLEUNIK',
        ),
        migrations.RenameField(
            model_name='ordres_frabrication',
            old_name='Temps_Prevu',
            new_name='GA_NBH',
        ),
        migrations.RenameField(
            model_name='ordres_frabrication',
            old_name='Phase_OF',
            new_name='PHASE',
        ),
        migrations.RemoveField(
            model_name='ordres_frabrication',
            name='Date_Debut',
        ),
        migrations.RemoveField(
            model_name='ordres_frabrication',
            name='Nom_Piece',
        ),
        migrations.RemoveField(
            model_name='ordres_frabrication',
            name='Rang_OF',
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='CLIENT_NOM',
            field=models.CharField(blank=True, default='XXX', max_length=50),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='DATE_CHARGE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='DATE_ORDO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='EN_PIECE',
            field=models.CharField(blank=True, default='XXX', max_length=100),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='ETATAF',
            field=models.CharField(blank=True, default='X', max_length=10),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='GA_NBHR',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='GA_PREP',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='HEURE_ORDO',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='NAF',
            field=models.CharField(blank=True, default='XXX', max_length=50),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='OF_Poste_ID',
            field=models.ForeignKey(default='C35-2', on_delete=django.db.models.deletion.CASCADE, to='BlogApp.poste', to_field='COFRAIS'),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='QTEAF',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='RANG',
            field=models.CharField(blank=True, default='XXX', max_length=50),
        ),
        migrations.AddField(
            model_name='ordres_frabrication',
            name='TYPEAF',
            field=models.CharField(blank=True, default='XXX', max_length=2),
        ),
        migrations.DeleteModel(
            name='Asso_Postes_OF',
        ),
    ]
