# Generated by Django 5.0.2 on 2024-03-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='weather',
            new_name='wthr',
        ),
    ]
