# Generated by Django 5.0.2 on 2024-06-18 09:08

import BlogApp.enums
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup_PDCMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default=BlogApp.enums.SetupStatus['active'], enum_class=BlogApp.enums.SetupStatus, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_interval', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('5 secs', '5 secs')], default=BlogApp.enums.TimeInterval['five_secs'], enum_class=BlogApp.enums.TimeInterval, max_length=6)),
                ('nom_poste', models.CharField(max_length=70)),
                ('num_semaine', models.IntegerField(blank=True, default=0)),
                ('num_annee', models.IntegerField(blank=True, default=0)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Setup_PDCMachine',
                'verbose_name_plural': 'Setups_PDCMachine',
            },
        ),
    ]
