# Generated by Django 5.0.2 on 2024-05-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_ordres_frabrication_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordres_Frabrication',
            new_name='Ordre_Frabrication',
        ),
    ]
