# Generated by Django 5.0.2 on 2024-03-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_rename_weather_weather_wthr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='wthr',
        ),
    ]
