# Generated by Django 5.0.2 on 2024-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_listeattenteordo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeattenteordo',
            name='TEMPS_ECOULE',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='listeattenteordo',
            name='TEMPS_PREVU',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='listeattenteordo',
            name='TEMPS_RESTANT',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
