# Generated by Django 5.0.2 on 2024-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_rename_ordres_frabrication_ordre_frabrication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordre_frabrication',
            name='GACLEUNIK',
            field=models.CharField(blank=True, default='XXX', max_length=50),
        ),
    ]
