# Generated by Django 5.0.2 on 2024-03-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_remove_weather_wthr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['dt_txt']},
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='date',
            new_name='dt_txt',
        ),
    ]
