# Generated by Django 5.0.2 on 2024-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_listeattenteordo_temps_ecoule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeattenteordo',
            name='DATE_DEBUT_ORDO',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
