# Generated by Django 5.0.2 on 2024-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_weather_options_rename_date_weather_dt_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='dt_txt',
            field=models.CharField(blank=True, default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(blank=True, default='default_value', max_length=50),
        ),
    ]
