# Generated by Django 5.0.2 on 2024-06-02 15:07

import BlogApp.enums
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_ordre_frabrication_gacleunik'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup_OF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default=BlogApp.enums.SetupStatus['active'], enum_class=BlogApp.enums.SetupStatus, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_interval', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('5 secs', '5 secs'), ('10 secs', '10 secs'), ('30 secs', '30 secs'), ('1 min', '1 min'), ('5 mins', '5 mins'), ('1 hour', '1 hour')], default=BlogApp.enums.TimeInterval['ten_secs'], enum_class=BlogApp.enums.TimeInterval, max_length=7)),
                ('nom_poste', models.CharField(default='C35-2', max_length=70)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Setup_OF',
                'verbose_name_plural': 'Setups_OF',
            },
        ),
    ]
