# Generated by Django 5.0.2 on 2024-03-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_alter_weather_dt_txt_alter_weather_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={},
        ),
        migrations.RemoveField(
            model_name='weather',
            name='dt_txt',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temp',
        ),
    ]
