# Generated by Django 5.0.2 on 2024-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_setup_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup_of',
            name='nom_poste',
            field=models.CharField(max_length=70),
        ),
    ]
