# Generated by Django 5.0.2 on 2024-05-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_planchargeatelier_alter_listeattenteordo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INDICATEUR_DESIGN', models.CharField(blank=True, default='XXX', max_length=50, unique=True)),
                ('Libelle_Atelier', models.CharField(blank=True, default='Atelier XXX', max_length=50)),
            ],
            options={
                'ordering': ['INDICATEUR_DESIGN'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Infos_Des',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Info_Des', models.CharField(blank=True, default='Com', max_length=50)),
                ('Descritpion_Info_Des', models.CharField(blank=True, default='None', max_length=200)),
            ],
            options={
                'ordering': ['Libelle_Info_Des'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ordres_Frabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_OF', models.CharField(blank=True, default='XXX', max_length=50, unique=True)),
                ('Nom_Piece', models.CharField(blank=True, default='Piece XXX', max_length=50)),
                ('Temps_Prevu', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15)),
                ('Date_Debut', models.DateTimeField(blank=True)),
                ('Phase_OF', models.IntegerField(blank=True, default=0)),
                ('Rang_OF', models.CharField(blank=True, default='X', max_length=50)),
            ],
            options={
                'ordering': ['Ref_OF'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COSECT', models.CharField(blank=True, default='ATXXX', max_length=10, unique=True)),
                ('Libelle_Site', models.CharField(blank=True, default='Site XXX', max_length=50)),
            ],
            options={
                'ordering': ['COSECT'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Absence', models.CharField(blank=True, default='Abs', max_length=50)),
                ('Type_Absence', models.CharField(blank=True, default='None', max_length=50)),
                ('Commentaire_Absence', models.CharField(blank=True, default='None', max_length=200)),
                ('Atelier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier')),
            ],
            options={
                'ordering': ['Libelle_Absence'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Infos_Asc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Info_Asc', models.CharField(blank=True, default='Info', max_length=50)),
                ('Descritpion_Info_Asc', models.CharField(blank=True, default='None', max_length=200)),
                ('Destinataire', models.CharField(blank=True, default='None', max_length=50)),
                ('Atelier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier')),
            ],
            options={
                'ordering': ['Libelle_Info_Asc'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asso_Atelier_Info_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atelier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier')),
                ('Info_Des_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.infos_des')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COFRAIS', models.CharField(blank=True, default='XXX', max_length=10, unique=True)),
                ('DESIGN', models.CharField(blank=True, default='Machine XXX', max_length=50)),
                ('VAR_AFF', models.BooleanField(default=1)),
                ('Atelier_ID', models.ForeignKey(default='XXX', on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier', to_field='INDICATEUR_DESIGN')),
                ('Site_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.site', to_field='COSECT')),
            ],
            options={
                'ordering': ['COFRAIS'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VDUREE', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('ANNEE', models.IntegerField(blank=True, default=0)),
                ('SEMAINE', models.IntegerField(blank=True, default=0)),
                ('Poste_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.poste', to_field='COFRAIS')),
            ],
            options={
                'ordering': ['VDUREE'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asso_Postes_OF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OF_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.ordres_frabrication', to_field='Ref_OF')),
                ('Poste_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.poste', to_field='COFRAIS')),
            ],
        ),
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_Accident', models.CharField(blank=True, default='Acc', max_length=50)),
                ('Description_Accident', models.CharField(blank=True, default='None', max_length=200)),
                ('Site_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.site')),
            ],
            options={
                'ordering': ['Libelle_Accident'],
                'managed': True,
            },
        ),
    ]
