# Generated by Django 5.0.2 on 2024-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_alter_weather_options_remove_weather_dt_txt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['dt']},
        ),
        migrations.AddField(
            model_name='weather',
            name='dt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='dt_txt',
            field=models.CharField(blank=True, default='default_value', max_length=50),
        ),
    ]
