# Generated by Django 5.0.2 on 2024-05-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_atelier_infos_des_ordres_frabrication_poste_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='Atelier_ID',
            field=models.ForeignKey(default='XXX', on_delete=django.db.models.deletion.CASCADE, to='BlogApp.atelier', to_field='INDICATEUR_DESIGN'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='INDICATEUR_DESIGN',
            field=models.CharField(blank=True, default='XXX', max_length=50, unique=True),
        ),
    ]
