# Generated by Django 5.0.2 on 2024-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_alter_weather_options_weather_dt_weather_dt_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='dt_txt',
        ),
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
