# Generated by Django 5.0.2 on 2024-03-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_remove_weather_dt_txt_weather_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['dt_txt']},
        ),
        migrations.RemoveField(
            model_name='weather',
            name='dt',
        ),
        migrations.AddField(
            model_name='weather',
            name='dt_txt',
            field=models.CharField(blank=True, default='default_value', max_length=50),
        ),
    ]
