# Generated by Django 5.0.2 on 2024-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_alter_setup_time_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='num_annee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='setup',
            name='num_semaine',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
