# Generated by Django 5.0.2 on 2024-05-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_alter_setup_time_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='nom_atelier',
            field=models.CharField(default='XXX', max_length=70),
        ),
        migrations.AddField(
            model_name='setup',
            name='nom_site',
            field=models.CharField(default='ATCRM', max_length=70),
        ),
    ]
