# Generated by Django 5.0.2 on 2024-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_setup_nom_atelier_setup_nom_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='VDUREE',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ordres_frabrication',
            name='Temps_Prevu',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
